### ISSUE TITLE
可以在存在子版块的时候删除板块分组

### ISSUE THREAD

**Issue by gentlespoon** [gentlespoon/hp-union.com#1]
如题。

**Comment by ghosind** [comment]
和帖子的处理方式类似吧，要么自动升至上一级，要么无法删除，要先移除子版块先。可以看看dz以及其他的论坛系统是怎么做的。我现在觉得提示无法删除较为妥当一点，但是和删除帖子一样，如果存在数量较多的子版块以及帖子处理起来会比较复杂，稍微考虑一下先吧。

**Comment by gentlespoon** [comment]
先做成无法删除吧 数量多也没问题- =
select 版块 where parent_fid={要删除的fid}; 结果非空就不删除

**Comment by ghosind** [comment]
恩   就先这样处理吧，暂时也没有其它好的处理方式了好像。
